# Welcome to Jekyll!

# Website settings
title: "rsnk"
description: "rsnk's blog?'"
keywords: "rsnk, rsnk96,Jalpc,blog,Jekyll,github,Nikhil"
baseurl: "/"
url: "https://rsnk96.github.io"

# author
author:
  name: 'rsnk'
  first_name: 'R S Nikhil Krishna'
  last_name: '.'
  email: 'rsnk96@gmail.com'
  facebook_username: 'rsnk96'
  github_username: 'rsnk96'
  head_img: 'static/img/landing/dp.jpg'
  desc: 'Why do I do what I do? Because "You either die a programmer, or live long enough to be the programmed". I am an undergraduate student at IIT Madras, programmer, numismatist, Music Lover (❤) and gamer. My current fields of interest include Computer Vision, Machine Learning, Reinforcement Learning, and AGI'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
# languages:
#   - locale: 'en'
#     flag: 'static/img/flags/United-States.png'
#   # - locale: 'zh'
  #   flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# # donate
# donate:
#   wechat: 'static/img/pay/wechat.png'
#   alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
# https://help.disqus.com/customer/portal/articles/787016-how-to-create-an-api-application
  name: rsnk96-github-io
  public_key: QynyAYpVI8Gwndf1jVKujxrZKeiu9N1nl4mlSfrvFifOmusa8O7Ta4zMQuqOyZfl

# share
bshare:
# COMMENTED OUT BY ME
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
# COMMENTED OUT BY ME
  # id: UA-73784599-1

# growingIO
gio:
# COMMENTED OUT BY ME
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
